extends Node


## CARD ANIMATIONS
const CARD_DRAW_DURATION = 0.4
const CARD_DRAW_FADE_DURATION = 0.15
const CARD_DRAW_SCALE_DURATION = 0.25
const CARD_DRAW_SCALE_SETTLE_DURATION = 0.1
const CARD_DRAW_ROTATION_DURATION = 0.2

const CARD_DISCARD_DURATION = 0.5
const CARD_DISCARD_ARC_DURATION_PHASE1 = 0.2  # Up phase
const CARD_DISCARD_ARC_DURATION_PHASE2 = 0.3  # Down phase  
const CARD_DISCARD_FADE_DURATION = 0.15
const CARD_DISCARD_ARC_HEIGHT = 100

const CARD_HOVER_DURATION = 0.3
const CARD_HOVER_UNHOVER_DURATION = 0.2
const CARD_PLAY_DURATION = 0.3

const CARD_HOVER_LIFT = -100
const CARD_HOVER_SCALE = Vector2(1.05, 1.05)
const CARD_DRAW_START_SCALE = Vector2(0.3, 0.3)
const CARD_DRAW_BOUNCE_SCALE = Vector2(1.1, 1.1)
const CARD_DRAW_FINAL_SCALE = Vector2(1.0, 1.0)
const CARD_DISCARD_END_SCALE = Vector2(0.3, 0.3)

const CARD_DRAW_ROTATION_RANGE = 5.0  # degrees +/-
const CARD_DISCARD_ROTATION_MIN = 60.0
const CARD_DISCARD_ROTATION_MAX = 120.0

## TOOLTIP ANIMATIONS
const TOOLTIP_SHOW_DURATION = 0.15
const TOOLTIP_HIDE_DURATION = 0.1
const TOOLTIP_DEFAULT_DELAY = 0.5
